- configuration/pih/htmlforms/hiv/zl/hiv-dispensing.xml
Hi @mogoodrich , I have refactored this form to include obs with answerDrugIds and answerLabels, and I ran into problems. I will document those issues in the ticket (UHM-4850). 
I create this PR just in case I set something incorrectly or if you want to pull in this updated form and test. Thanks!
> UHM-4850, saving dispensing drugs

- configuration/pih/htmlforms/hiv/zl/hiv-dispensing.xml
Here is the implementation for the data validations outlined in https://pihemr.atlassian.net/browse/UHM-4830. Thanks! @mseaton , @mogoodrich , @brandones
> UHM-4830, add data entry validations

- configuration/pih/htmlforms/hiv/zl/hiv-dispensing.xml
Hi @mogoodrich , I saw you have used REST and AJAX calls in other html forms, so I follow that example to add a small REST call to get the last prescribed regimen obsgroup. Thanks for reviewing!
> UHM-4851, display last prescribed regimen

- configuration/pih/htmlforms/hiv/zl/section-hiv-history.xml
- configuration/pih/htmlforms/hiv/zl/section-hiv-state.xml
Hi @lnball , here are the changes I made to the TB screening form to include the additional questions. Thanks!
> UHM-4976, additional TB screening questions

- configuration/pih/htmlforms/hiv/section-hiv-plan.xml
See discussion in comments section here:
https://pihemr.atlassian.net/browse/UHM-5103
> Change concept used for "TB continue treatment", see UHM-5103

- configuration/pih/htmlforms/hiv/section-hiv-plan.xml
Just creating this PR to demonstrate what I have in place so far.  I'm not ready to commit yet, as there are a few issues still to work out.  But figured I could use this PR to show what the tag config looks like so far, and throw a few screenshots up for review.  Please let me know if you have any feedback.
> Initial pass at demonstrating drug order tag usage for ART.

- configuration/pih/htmlforms/hiv/section-hiv-history.xml
- configuration/pih/htmlforms/hiv/section-hiv-state.xml
I think I over-engineered a little bit but I got it working as described in the ticket:
https://pihemr.atlassian.net/browse/UHM-5088?focusedCommentId=111493
> UHM-5088, collect CHW name on the HIV initial and followup forms

- configuration/pih/htmlforms/hiv/section-hiv-history.xml
- configuration/pih/htmlforms/hiv/section-hiv-state.xml
Please see also https://github.com/PIH/openmrs-config-pihemr/pull/109
https://pihemr.atlassian.net/browse/UHM-5093
> UHM-5093 Capture HIV Contacts for new HIV patients

- configuration/pih/htmlforms/hiv/section-hiv-plan_v3.0.xml
Lots of little tweaks to commented out V3, so hopefully this works now.
@mogoodrich Send back to me if it's bad.
> UHM-5209-A Test of V3 of the HIV Plan form

- configuration/pih/htmlforms/hiv/section-hiv-plan_v3.0.xml
https://pihemr.atlassian.net/browse/UHM-3134
Change for Lab Results TBD
> UHM-3134: Add read-only provider box to Plan section

- configuration/pih/htmlforms/hiv/section-hiv-plan_v3.0.xml
> Simplify provider section in plan v3

- configuration/pih/htmlforms/hiv/section-hiv-plan.xml
- configuration/pih/htmlforms/hiv/section-hiv-plan_v3.0.xml
https://pihemr.atlassian.net/browse/UHM-5284
> UHM-5284 Update HIV Intake prophylaxis treatment htmlform

- configuration/pih/htmlforms/hiv/section-hiv-plan.xml
- configuration/pih/htmlforms/hiv/section-hiv-plan_v3.0.xml
https://pihemr.atlassian.net/browse/UHM-5284
> Fix message codes to correct tense

- configuration/pih/htmlforms/hiv/section-hiv-plan_v3.0.xml
https://pihemr.atlassian.net/browse/UHM-5349
Trivial; will merge
> Fix label of 'other prophylaxis'

- configuration/pih/htmlforms/hiv/section-hiv-plan_v3.0.xml
https://pihemr.atlassian.net/browse/UHM-5349
> UHM-5349: Fix other label (again)

- configuration/pih/styles/global/zl.css
Working space until I get it reviewed by John Ra...  Keep tweaking...
> UHM-4184 Updated PIH colors

- configuration/pih/pih-config-haiti-hsn-ci.json
- configuration/pih/pih-config-mirebalais-humci.json
See https://github.com/PIH/openmrs-module-mirebalais/pull/170
> Enable SPA Preview for CI servers

- configuration/pih/pih-config-haiti-belladere.json
- configuration/pih/pih-config-haiti-boucancarre.json
- configuration/pih/pih-config-haiti-hsn-ci.json
- configuration/pih/pih-config-haiti-hsn.json
- configuration/pih/pih-config-haiti-lacolline.json
- configuration/pih/pih-config-haiti-mentalhealth.json
- configuration/pih/pih-config-haiti-thomonde-ci.json
- configuration/pih/pih-config-haiti-thomonde.json
- configuration/pih/pih-config-haiti.json
- configuration/pih/pih-config-mirebalais-humci.json
- configuration/pih/pih-config-mirebalais-humdemo.json
- configuration/pih/pih-config-mirebalais-production.json
- configuration/pih/pih-config-mirebalais-training.json
https://pihemr.atlassian.net/browse/UHM-5509
> UHM-5509 Enable "Mark Patient Died" functionality on all servers

- configuration/pih/htmlforms/hiv/section-hiv-history.xml
- configuration/pih/htmlforms/hiv/section-pmtct-history.xml
- configuration/pih/scripts/global/zl.js
https://pihemr.atlassian.net/browse/UHM-5676
> UHM-5676 Fix gestational age calculation

- configuration/pih/htmlforms/hiv/section-pmtct-history.xml
- configuration/pih/styles/global/zl.css
@lnball @dmdesimone 
Please review this PR.
> UHM-5715- Improve display of PMTCT contacts on encounter display

- configuration/pih/scripts/global/zl.js
@mogoodrich @brandones 
Please review this PR
>  UHM-5691-CD - Default to showing contacts with data for PMTCT and HIV

- configuration/pih/htmlforms/hiv/section-hiv-state.xml
- configuration/pih/htmlforms/hiv/section-pmtct-history.xml
> UHM-5749- Add evaluation of continued treatment section on PMTCT forms

- configuration/reports/reportdescriptors/dataexports/sql/socialEconomics.sql
> add J9 fields

- configuration/reports/reportdescriptors/dataexports/sql/socialEconomics.sql
break assistance into individual columns
> break assistance into columns

- configuration/pih/htmlforms/hiv/hiv-dispensing.xml
- configuration/pih/htmlforms/hiv/section-hiv-plan.xml
At this late date, I don't want to make changes to the HIV forms without review.
> UHM-5973 Added B6 (vitamin) to drug order and hiv dispensing

- configuration/pih/htmlforms/hiv/section-hiv-state.xml
- configuration/pih/htmlforms/hiv/section-pmtct-history.xml
- configuration/pih/scripts/global/zl.js
(fix obs with obs dated function)
> UHM-5918: Date Validation javascript function issues

- configuration/pih/htmlforms/hiv/section-hiv-state.xml
- configuration/pih/htmlforms/hiv/section-pmtct-history.xml
- configuration/pih/scripts/global/zl.js
@mogoodrich please review this PR
> UHM-5972: code refactoring for Fix start and end dates for syphilis

- configuration/pih/htmlforms/hiv/section-pmtct-history.xml
@lnball please review this PR
**English translation**
```
pihcore.hiv_status_cat=HIV known status category
pihcore.hiv_test_received=Received HIV test result
pihcore.has_posttest_counseling=HIV/AIDS counseling
pihcore.services_status=Services status
```
**French translations**
```
pihcore.hiv_status_cat=Catégorie de statut VIH connu
pihcore.hiv_test_received=Résultat du test VIH reçu
pihcore.has_posttest_counseling=Conseil VIH/SIDA
pihcore.services_status=État des services
```
> UHM-5983: Additional fields for PMTCT contacts

- configuration/pih/htmlforms/hiv/section-pmtct-history.xml
I did a lot of whitespace fixing; use the "hide whitespace changes" feature when viewing the diff.
Shown is the message code added here: https://github.com/PIH/openmrs-config-pihemr/pull/318
Translations are still needed.
> UHM-6071 Add fields to PMTCT Intake form

- configuration/pih/htmlforms/hiv/section-hiv-history.xml
https://pihemr.atlassian.net/browse/UHM-6101
> UHM-6101 Add breastfeeding question for PMTCT KPI

- configuration/pih/htmlforms/hiv/eid-followup.xml
- configuration/pih/htmlforms/hiv/hiv-followup.xml
- configuration/pih/htmlforms/hiv/hiv-followup_v1.0.xml
- configuration/pih/htmlforms/hiv/hiv-followup_v2.0.xml
- configuration/pih/htmlforms/hiv/hiv-followup_v3.0.xml
- configuration/pih/htmlforms/hiv/hiv-intake.xml
- configuration/pih/htmlforms/hiv/hiv-intake_v1.0.xml
- configuration/pih/htmlforms/hiv/hiv-intake_v2.0.xml
- configuration/pih/htmlforms/hiv/hiv-intake_v3.0.xml
- configuration/pih/htmlforms/hiv/pmtct-followup.xml
- configuration/pih/htmlforms/hiv/pmtct-intake.xml
- configuration/pih/htmlforms/hiv/section-eid-protection.xml
- configuration/pih/htmlforms/hiv/section-hiv-assessment.xml
- configuration/pih/htmlforms/hiv/section-risk-factors.xml
- configuration/pih/htmlforms/hiv/section-symptoms.xml
Touches a ton of forms, but hopefully will simplify things...we no longer require a custom piece of javascript per form. Requires PIH Core change to do in first, so please don't merge.
> UHM-6136: View/Edit page for saved forms

- configuration/pih/htmlforms/hiv/hiv-dispensing.xml
Please review this PR @lnball @rjacques89 @mogoodrich
> HAI-668:Add DTG 5mg to the list of drugs

- configuration/pih/htmlforms/hiv/section-hiv-plan.xml
- configuration/pih/scripts/global/zl.js
> HAI-697: Add validation to HIV return visit date

- configuration/pih/htmlforms/hiv/section-hiv-plan.xml
> added double quotes instead of single quotes for message parameters

- configuration/messageproperties/messages_zl_en.properties
- configuration/messageproperties/messages_zl_fr.properties
- configuration/messageproperties/messages_zl_ht.properties
- configuration/pih/statusData/hiv/hivStatuses.yml
- configuration/pih/statusData/hiv/lastDispensedMedication.sql
@mogoodrich suggested that I added two set of information for the regimen :
- The last dispensed medication set (ARV1 -ARV2- ARV3)
- The last prescribed medication set from the orders.
Here I added the last dispensed set.
> Add last dispensed medication to vih dashboard

- configuration/messageproperties/messages_zl_en.properties
- configuration/messageproperties/messages_zl_fr.properties
- configuration/pih/statusData/hiv/firstArtStartDate.sql
- configuration/pih/statusData/hiv/hivStatuses.yml
> Adding the date of the ARV coating on the patient's dashboard

- configuration/pih/pih-config-haiti-hiv.json
please review this PR @mogoodrich
> HAI-736:Add ability to add column that shows patient identifier location

- configuration/pih/htmlforms/hiv/section-hiv-plan.xml
@mogoodrich Please review this PR
> Bug in the return date of the visit fixed

- configuration/pih/htmlforms/hiv/hiv-dispensing.xml
@lnball or @mogoodrich Review this PR.
> Dapsone 100 mg added to the list of dispensing drugs

- configuration/pih/htmlforms/patientRegistration-contact.xml
- configuration/pih/scripts/global/zl.js
This function "setUpNextAndSubmitButtons" does not work, in "patientRegistration-contact.xml". for this reason I added the function directly :> 
FYI @mogoodrich , @brandones , @lnball
> HAI-709: Submit button disabled when phone number is incorrect

- configuration/pih/htmlforms/checkin.xml
- configuration/pih/scripts/global/zl.js
> Limiter au numero de recu numerique

- configuration/pih/htmlforms/hiv/section-hiv-history.xml
- configuration/pih/htmlforms/hiv/section-hiv-state.xml
- configuration/pih/scripts/global/zl.js
> HAI-845: INH dates display issue when only INH line is entered

- configuration/messageproperties/messages_zl_en.properties
- configuration/messageproperties/messages_zl_fr.properties
- configuration/messageproperties/messages_zl_ht.properties
- configuration/pih/htmlforms/hiv/section-hiv-plan.xml
> HAI-855: add 'yes, but other reason' to Does patient require ART

- configuration/pih/htmlforms/hiv/section-hiv-history.xml
- configuration/pih/htmlforms/hiv/section-pmtct-history.xml
- configuration/pih/scripts/global/zl.js
> HAI-858: Require that information on mode of transmission and other risk factors be systematically provided.

- configuration/pih/htmlforms/hiv/section-pmtct-history.xml
- configuration/pih/statusData/hiv/hivStatuses.yml
- configuration/pih/statusData/hiv/lastPregnancyStatus.sql
Please review this PR.
FYI: @mogoodrich, @dmdesimone
> Update pregnant status after PTME Initial and followup which specifies pregnant and change status when due date added

- configuration/messageproperties/messages_zl_en.properties
- configuration/messageproperties/messages_zl_fr.properties
- configuration/pih/statusData/hivTb/coinfectionStatus.sql
- configuration/pih/statusData/hivTb/statuses.yml
> HA-716-update: Add coinfection status to patient dashboard

- configuration/pih/htmlforms/hiv/section-hiv-history.xml
- configuration/pih/htmlforms/hiv/section-hiv-state.xml
- configuration/pih/htmlforms/hiv/section-pmtct-history.xml
- configuration/pih/scripts/global/zl.js
I have corrected the message display
FYI: @mogoodrich , @dmdesimone
> HAI-845 and HAI-858 ticket correction

- configuration/pih/htmlforms/hiv/section-hiv-plan.xml
- configuration/pih/scripts/global/zl.js
> add 'yes, but delayed for a medical reason' for ART treatment questions

- configuration/pih/htmlforms/hiv/section-hiv-plan.xml
> Text reason added

- configuration/pih/scripts/global/zl.js
Hi @mogoodrich @dmdesimone @mseaton , have a look on PR please
> Alert the clinician on updating patient info

- configuration/pih/htmlforms/hiv/section-hiv-plan.xml
> Add additional reasons for patient requiring ART

- configuration/pih/statusData/hiv/hivPatientStatus.sql
@dmdesimone Please check this out to see if the error goes
> fixing issue

- configuration/pih/statusData/hiv/hivPatientStatus.sql
@dmdesimone Have a look please.
> fixing bug

- configuration/messageproperties/messages_zl_en.properties
- configuration/messageproperties/messages_zl_fr.properties
- configuration/pih/htmlforms/hiv/section-hiv-history.xml
- configuration/pih/htmlforms/hiv/section-hiv-state.xml
> Add delivery question to hiv intake and followup

- configuration/messageproperties/messages_zl_en.properties
- configuration/messageproperties/messages_zl_fr.properties
- configuration/pih/statusData/hiv/hivStatuses.yml
translating hiv status @dmdesimone
> translating hiv status

- configuration/pih/statusData/hiv/hivStatuses.yml
> change variable name

- configuration/pih/statusData/hiv/hivPatientStatus.sql
- configuration/pih/statusData/hiv/hivStatuses.yml
@dmdesimone  have a look please
> fixing locale issue

- configuration/pih/htmlforms/hiv/section-hiv-state.xml
> bug fixing in delivery section

- configuration/pih/htmlforms/hiv/section-hiv-history.xml
This validation function was included even if the transmission section was not included for children. I have just moved the validation function within the conditional clause. Thanks @mogoodrich for reviewing this change!
> UHM-7624, add validation function conditionally if section is included

- configuration/programworkflows/zlncd.csv
- configuration/programworkflowstates/zlncd.csv
3 PRs for this change.  This one for ZL
> UHM-7707 Moved NCD program workflows from pihemr to zl config

- configuration/pih/statusData/hivTb/inhStatus.sql
> HAI-940:Update INH display in clinical dashboard

- configuration/messageproperties/messages_zl_en.properties
- configuration/messageproperties/messages_zl_fr.properties
- configuration/pih/htmlforms/hiv/hiv-psychosocial.xml
> HAI-927: Create HIV Psychosocial form

- configuration/pih/htmlforms/hiv/hiv-psychosocial.xml
> CHW workflow fixed

- configuration/pih/htmlforms/hiv/hiv-dispensing.xml
Removed the checkbox; Add the distributed in community to a radio button.
> HAI-948 Moved med dispensed in the community to radio button

- configuration/locationtagmaps/locationtagmaps-site-mirebalais.csv
> Active Primary Care Consult Location in Klinik Exten location at HUM

- content/pom.xml
Just want to confirm this is the correct revision to match the content package to the parent project.  Please let me know if there are additional updates needed.
> Update content pom.xml

- configuration/pih/htmlforms/vitalsInpatient.xml
remove Foetal Hearth Rate field from  '' Sal apre Akouchman  
it should only be in 'Sante Fanm"
> remove Foetal Hearth Rate field from 'Sal Fanm'

- configuration/pih/pih-config-haiti-mentalhealth-belladere.json
> UHM-8420: Setup Puppet and Config for Belladare MH

- configuration/reports/reportdescriptors/dataexports/sql/msppReport.sql
> New and Subsequent vist fixed

- configuration/pih/pih-config-haiti-mentalhealth-boucancarre.json
Boucan Carre MH config based on the json added for Belladere MH.
> UHM-8535 Add config for Boucan Carre MH

- configuration/reports/reportdescriptors/dataexports/sql/msppReport.sql
HAI-1042:NAISSANCES & SUIVI POST NATAL IS DONE
> HAI-1041:NAISSANCES & SUIVI POST NATAL IS DONE

- configuration/reports/reportdescriptors/dataexports/sql/msppReportTwo.sql
> HAI-1045-Split second try

- configuration/messageproperties/messages_zl_en.properties
- configuration/messageproperties/messages_zl_fr.properties
- configuration/pih/pih-config-haiti-hiv.json
> HAI-736: Afficher le site auquel appartient un patient lors de la recherche
